### ISSUE TITLE
Unsafe SVGs

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/vip-code-samples#36]
Would be great to have an example of what to look for in an unsafe SVG.

**Comment by nielslange** [comment]
@rebeccahum SVGs can contain malicious JS code. On https://flaviocopes.com/svg/#javascript-inside-svg you can find examples of JS code embedded into SVGs. Thus, what makes SVGs unsafe it embedded JS code. That said, it would still be good having a few examples.
